name: 'Test Report'
on:
  workflow_run:
    workflows: ['Run Tests']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    - name: Download workflow artifact
      uses: actions/download-artifact@v4
      with:
        name: test-results
        run_id: ${{ github.event.workflow_run.id }}
    - name: Set pr number env
      run: |
        PR_NUMBER=$(cat pr_number)
        echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
    - name: Test Report
      uses: phoenix-actions/test-reporting@v13
      id: test-report
      with:
        name: Mocha Tests
        path: backend/test-results.json
        reporter: mocha-json
