name: Run Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install hunspell
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm start &
      - uses: ifaxity/wait-on-action@v1.1.0
        with:
          delay: 1
          timeout: 30000
          resource: tcp:localhost:8082
      - run: npm run test-report
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > ./pr_number
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: |
            backend/test-results.json
            pr_number
